# ALM Configuration File

data:
  root_dir: "."
  metadata_file: "master_metadata.csv"
  sample_rate: 16000
  max_duration: 10.0
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

models:
  transcription:
    model_name: "facebook/wav2vec2-base-960h"
    device: "cpu"
    batch_size: 4
    max_length: 512
  
  emotion:
    model_name: "facebook/wav2vec2-base"
    num_classes: 5
    emotions: ["anger", "disgust", "fear", "happiness", "sadness"]
    device: "cpu"
    batch_size: 8
  
  cultural_context:
    model_name: "facebook/wav2vec2-base"
    num_classes: 2
    contexts: ["speech", "non-speech"]
    device: "cpu"
    batch_size: 8

training:
  epochs: 10
  learning_rate: 1e-4
  weight_decay: 1e-5
  patience: 5
  save_dir: "checkpoints"
  log_dir: "logs"

inference:
  device: "cuda"
  batch_size: 1
  output_format: "json"

api:
  host: "0.0.0.0"
  port: 8000
  debug: false
